-- MySQL Script generated by MySQL Workbench
-- Sun Oct 23 17:37:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`user` (
  `iduser` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`trainer` (
  `idtrainer` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `size` FLOAT NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`idtrainer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`order` (
  `idorder` INT NOT NULL,
  `delivery_adress` VARCHAR(45) NOT NULL,
  `status` ENUM("confirmation", "shipping", "completed") NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idorder`),
  INDEX `fk_order_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shop`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`order_and_trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`order_and_trainer` (
  `order_id` INT NOT NULL,
  `trainer_id` INT NOT NULL,
  `count` INT NOT NULL,
  INDEX `fk_order_and_trainer_order_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_and_trainer_trainer1_idx` (`trainer_id` ASC) VISIBLE,
  PRIMARY KEY (`count`),
  CONSTRAINT `fk_order_and_trainer_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `shop`.`order` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_and_trainer_trainer1`
    FOREIGN KEY (`trainer_id`)
    REFERENCES `shop`.`trainer` (`idtrainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
